//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsUsuarios
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://tempuri.org/")]
    public partial class LoginResponse : object
    {
        
        private bool SuccessField;
        
        private string MessagesField;
        
        private string NombreField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUsuarios.wsUsuariosSoap")]
    public interface wsUsuariosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<wsUsuarios.ValidateLoginResponse> ValidateLoginAsync(wsUsuarios.ValidateLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<wsUsuarios.RegistroUsuariosResponse> RegistroUsuariosAsync(wsUsuarios.RegistroUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLogin", Namespace="http://tempuri.org/", Order=0)]
        public wsUsuarios.ValidateLoginRequestBody Body;
        
        public ValidateLoginRequest()
        {
        }
        
        public ValidateLoginRequest(wsUsuarios.ValidateLoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public ValidateLoginRequestBody()
        {
        }
        
        public ValidateLoginRequestBody(int id, string username, string email, string password)
        {
            this.id = id;
            this.username = username;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsUsuarios.ValidateLoginResponseBody Body;
        
        public ValidateLoginResponse()
        {
        }
        
        public ValidateLoginResponse(wsUsuarios.ValidateLoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLoginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsUsuarios.LoginResponse ValidateLoginResult;
        
        public ValidateLoginResponseBody()
        {
        }
        
        public ValidateLoginResponseBody(wsUsuarios.LoginResponse ValidateLoginResult)
        {
            this.ValidateLoginResult = ValidateLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuariosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public wsUsuarios.RegistroUsuariosRequestBody Body;
        
        public RegistroUsuariosRequest()
        {
        }
        
        public RegistroUsuariosRequest(wsUsuarios.RegistroUsuariosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroUsuariosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public RegistroUsuariosRequestBody()
        {
        }
        
        public RegistroUsuariosRequestBody(int id, string username, string email, string password)
        {
            this.id = id;
            this.username = username;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsUsuarios.RegistroUsuariosResponseBody Body;
        
        public RegistroUsuariosResponse()
        {
        }
        
        public RegistroUsuariosResponse(wsUsuarios.RegistroUsuariosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroUsuariosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsUsuarios.LoginResponse RegistroUsuariosResult;
        
        public RegistroUsuariosResponseBody()
        {
        }
        
        public RegistroUsuariosResponseBody(wsUsuarios.LoginResponse RegistroUsuariosResult)
        {
            this.RegistroUsuariosResult = RegistroUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsUsuariosSoapChannel : wsUsuarios.wsUsuariosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsUsuariosSoapClient : System.ServiceModel.ClientBase<wsUsuarios.wsUsuariosSoap>, wsUsuarios.wsUsuariosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsUsuariosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsUsuariosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsUsuariosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsUsuariosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsUsuariosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsUsuariosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsUsuariosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsUsuarios.ValidateLoginResponse> wsUsuarios.wsUsuariosSoap.ValidateLoginAsync(wsUsuarios.ValidateLoginRequest request)
        {
            return base.Channel.ValidateLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsUsuarios.ValidateLoginResponse> ValidateLoginAsync(int id, string username, string email, string password)
        {
            wsUsuarios.ValidateLoginRequest inValue = new wsUsuarios.ValidateLoginRequest();
            inValue.Body = new wsUsuarios.ValidateLoginRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((wsUsuarios.wsUsuariosSoap)(this)).ValidateLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsUsuarios.RegistroUsuariosResponse> wsUsuarios.wsUsuariosSoap.RegistroUsuariosAsync(wsUsuarios.RegistroUsuariosRequest request)
        {
            return base.Channel.RegistroUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsUsuarios.RegistroUsuariosResponse> RegistroUsuariosAsync(int id, string username, string email, string password)
        {
            wsUsuarios.RegistroUsuariosRequest inValue = new wsUsuarios.RegistroUsuariosRequest();
            inValue.Body = new wsUsuarios.RegistroUsuariosRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((wsUsuarios.wsUsuariosSoap)(this)).RegistroUsuariosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsUsuariosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsUsuariosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsUsuariosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44338/wsUsuarios.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsUsuariosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44338/wsUsuarios.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsUsuariosSoap,
            
            wsUsuariosSoap12,
        }
    }
}
