SELECT TOP (1000) [Dia]
      ,[Mes]
      ,[Descripcion]
      ,[TipoFeriadoId]
      ,[ProporcionDia]
      ,[Usr_creacion]
      ,[Fec_creacion]
      ,[Usr_modifica]
      ,[Fec_modifica]
  FROM [DBProyectoGrupalDojoGeko].[dbo].[DiasFestivosFijos]
