SELECT TOP (1000) [Id]
      ,[Fecha]
      ,[Descripcion]
      ,[TipoFeriadoId]
      ,[ProporcionDia]
      ,[Usr_creacion]
      ,[Fec_creacion]
      ,[Usr_modifica]
      ,[Fec_modifica]
  FROM [DBProyectoGrupalDojoGeko].[dbo].[DiasFestivosVariables]
