//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipoCambio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class InfoVariable : object
    {
        
        private TipoCambio.Variable[] VariablesField;
        
        private TipoCambio.Var[] CambioDiaField;
        
        private TipoCambio.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TipoCambio.Variable[] Variables
        {
            get
            {
                return this.VariablesField;
            }
            set
            {
                this.VariablesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TipoCambio.Var[] CambioDia
        {
            get
            {
                return this.CambioDiaField;
            }
            set
            {
                this.CambioDiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TipoCambio.VarDolar[] CambioDolar
        {
            get
            {
                return this.CambioDolarField;
            }
            set
            {
                this.CambioDolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Variable : object
    {
        
        private int monedaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Var : object
    {
        
        private int monedaField;
        
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra
        {
            get
            {
                return this.compraField;
            }
            set
            {
                this.compraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VarDolar : object
    {
        
        private string fechaField;
        
        private float referenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class DataVariable : object
    {
        
        private TipoCambio.Var[] VarsField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TipoCambio.Var[] Vars
        {
            get
            {
                return this.VarsField;
            }
            set
            {
                this.VarsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="TipoCambio.TipoCambioSoap")]
    public interface TipoCambioSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync(TipoCambio.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.VariablesResponse> VariablesAsync(TipoCambio.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(TipoCambio.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(TipoCambio.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(TipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(TipoCambio.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync(TipoCambio.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(TipoCambio.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest()
        {
        }
        
        public VariablesDisponiblesRequest(TipoCambio.VariablesDisponiblesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody
    {
        
        public VariablesDisponiblesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse()
        {
        }
        
        public VariablesDisponiblesResponse(TipoCambio.VariablesDisponiblesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody()
        {
        }
        
        public VariablesDisponiblesResponseBody(TipoCambio.InfoVariable VariablesDisponiblesResult)
        {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.VariablesRequestBody Body;
        
        public VariablesRequest()
        {
        }
        
        public VariablesRequest(TipoCambio.VariablesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody()
        {
        }
        
        public VariablesRequestBody(int variable)
        {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.VariablesResponseBody Body;
        
        public VariablesResponse()
        {
        }
        
        public VariablesResponse(TipoCambio.VariablesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.InfoVariable VariablesResult;
        
        public VariablesResponseBody()
        {
        }
        
        public VariablesResponseBody(TipoCambio.InfoVariable VariablesResult)
        {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest()
        {
        }
        
        public TipoCambioFechaInicialRequest(TipoCambio.TipoCambioFechaInicialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody()
        {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit)
        {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse()
        {
        }
        
        public TipoCambioFechaInicialResponse(TipoCambio.TipoCambioFechaInicialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody()
        {
        }
        
        public TipoCambioFechaInicialResponseBody(TipoCambio.DataVariable TipoCambioFechaInicialResult)
        {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest()
        {
        }
        
        public TipoCambioRangoRequest(TipoCambio.TipoCambioRangoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody()
        {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse()
        {
        }
        
        public TipoCambioRangoResponse(TipoCambio.TipoCambioRangoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody()
        {
        }
        
        public TipoCambioRangoResponseBody(TipoCambio.DataVariable TipoCambioRangoResult)
        {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequest(TipoCambio.TipoCambioFechaInicialMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda)
        {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponse(TipoCambio.TipoCambioFechaInicialMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(TipoCambio.DataVariable TipoCambioFechaInicialMonedaResult)
        {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest()
        {
        }
        
        public TipoCambioRangoMonedaRequest(TipoCambio.TipoCambioRangoMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody()
        {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse()
        {
        }
        
        public TipoCambioRangoMonedaResponse(TipoCambio.TipoCambioRangoMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody()
        {
        }
        
        public TipoCambioRangoMonedaResponseBody(TipoCambio.DataVariable TipoCambioRangoMonedaResult)
        {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest()
        {
        }
        
        public TipoCambioDiaRequest(TipoCambio.TipoCambioDiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody
    {
        
        public TipoCambioDiaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse()
        {
        }
        
        public TipoCambioDiaResponse(TipoCambio.TipoCambioDiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TipoCambio.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody()
        {
        }
        
        public TipoCambioDiaResponseBody(TipoCambio.InfoVariable TipoCambioDiaResult)
        {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest()
        {
        }
        
        public TipoCambioDiaStringRequest(TipoCambio.TipoCambioDiaStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody
    {
        
        public TipoCambioDiaStringRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TipoCambio.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse()
        {
        }
        
        public TipoCambioDiaStringResponse(TipoCambio.TipoCambioDiaStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody()
        {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult)
        {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface TipoCambioSoapChannel : TipoCambio.TipoCambioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<TipoCambio.TipoCambioSoap>, TipoCambio.TipoCambioSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), TipoCambioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.VariablesDisponiblesResponse> TipoCambio.TipoCambioSoap.VariablesDisponiblesAsync(TipoCambio.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync()
        {
            TipoCambio.VariablesDisponiblesRequest inValue = new TipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new TipoCambio.VariablesDisponiblesRequestBody();
            return ((TipoCambio.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.VariablesResponse> TipoCambio.TipoCambioSoap.VariablesAsync(TipoCambio.VariablesRequest request)
        {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.VariablesResponse> VariablesAsync(int variable)
        {
            TipoCambio.VariablesRequest inValue = new TipoCambio.VariablesRequest();
            inValue.Body = new TipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((TipoCambio.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialResponse> TipoCambio.TipoCambioSoap.TipoCambioFechaInicialAsync(TipoCambio.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit)
        {
            TipoCambio.TipoCambioFechaInicialRequest inValue = new TipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new TipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoResponse> TipoCambio.TipoCambioSoap.TipoCambioRangoAsync(TipoCambio.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin)
        {
            TipoCambio.TipoCambioRangoRequest inValue = new TipoCambio.TipoCambioRangoRequest();
            inValue.Body = new TipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambio.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(TipoCambio.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda)
        {
            TipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new TipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoMonedaResponse> TipoCambio.TipoCambioSoap.TipoCambioRangoMonedaAsync(TipoCambio.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda)
        {
            TipoCambio.TipoCambioRangoMonedaRequest inValue = new TipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new TipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaResponse> TipoCambio.TipoCambioSoap.TipoCambioDiaAsync(TipoCambio.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync()
        {
            TipoCambio.TipoCambioDiaRequest inValue = new TipoCambio.TipoCambioDiaRequest();
            inValue.Body = new TipoCambio.TipoCambioDiaRequestBody();
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaStringResponse> TipoCambio.TipoCambioSoap.TipoCambioDiaStringAsync(TipoCambio.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync()
        {
            TipoCambio.TipoCambioDiaStringRequest inValue = new TipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new TipoCambio.TipoCambioDiaStringRequestBody();
            return ((TipoCambio.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TipoCambioSoap,
            
            TipoCambioSoap12,
        }
    }
}
