SELECT TOP (1000) [Id]
      ,[Destinatario]
      ,[CC]
      ,[Asunto]
      ,[Cuerpo]
      ,[RutaAdjunto]
      ,[Estado]
      ,[FechaCreacion]
  FROM [SistemaSeguridad].[dbo].[CorreosPendientes]
