//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoAPIswAuthentication.wsUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUsuarios.wsUsuariosSoap")]
    public interface wsUsuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateLogin", ReplyAction="*")]
        ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse ValidateLogin(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse> ValidateLoginAsync(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLogin", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequestBody Body;
        
        public ValidateLoginRequest() {
        }
        
        public ValidateLoginRequest(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateLoginRequestBody() {
        }
        
        public ValidateLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponseBody Body;
        
        public ValidateLoginResponse() {
        }
        
        public ValidateLoginResponse(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoAPIswAuthentication.wsUsuarios.LoginResponse ValidateLoginResult;
        
        public ValidateLoginResponseBody() {
        }
        
        public ValidateLoginResponseBody(ConsumoAPIswAuthentication.wsUsuarios.LoginResponse ValidateLoginResult) {
            this.ValidateLoginResult = ValidateLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsUsuariosSoapChannel : ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsUsuariosSoapClient : System.ServiceModel.ClientBase<ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap>, ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap {
        
        public wsUsuariosSoapClient() {
        }
        
        public wsUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap.ValidateLogin(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest request) {
            return base.Channel.ValidateLogin(request);
        }
        
        public ConsumoAPIswAuthentication.wsUsuarios.LoginResponse ValidateLogin(string username, string password) {
            ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest inValue = new ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest();
            inValue.Body = new ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse retVal = ((ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap)(this)).ValidateLogin(inValue);
            return retVal.Body.ValidateLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse> ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap.ValidateLoginAsync(ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest request) {
            return base.Channel.ValidateLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginResponse> ValidateLoginAsync(string username, string password) {
            ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest inValue = new ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequest();
            inValue.Body = new ConsumoAPIswAuthentication.wsUsuarios.ValidateLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ConsumoAPIswAuthentication.wsUsuarios.wsUsuariosSoap)(this)).ValidateLoginAsync(inValue);
        }
    }
}
